"""Added analytics table for power usage

Revision ID: 7a5ac00bd997
Revises: c698a505fe3d
Create Date: 2024-01-22 09:14:32.362395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5ac00bd997'
down_revision: Union[str, None] = 'c698a505fe3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_power_usage_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('power_usage_5_minutes_ahead', sa.Float(), nullable=True),
    sa.Column('power_usage_15_minutes_ahead', sa.Float(), nullable=True),
    sa.Column('power_usage_60_minutes_ahead', sa.Float(), nullable=True),
    sa.Column('power_usage_5_minutes_ahead_forecast', sa.Float(), nullable=True),
    sa.Column('power_usage_15_minutes_ahead_forecast', sa.Float(), nullable=True),
    sa.Column('power_usage_60_minutes_ahead_forecast', sa.Float(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_power_usage_analytics')
    # ### end Alembic commands ###
