"""power usage api logging

Revision ID: b4067adf9f8c
Revises: 75bf256ae396
Create Date: 2024-01-21 21:02:09.686759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4067adf9f8c'
down_revision: Union[str, None] = '75bf256ae396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_power_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('power_usage_5_minutes_ahead', sa.Float(), nullable=True),
    sa.Column('power_usage_15_minutes_ahead', sa.Float(), nullable=True),
    sa.Column('power_usage_60_minutes_ahead', sa.Float(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_power_usage')
    # ### end Alembic commands ###
