"""Added the API version

Revision ID: c698a505fe3d
Revises: bcb853436519
Create Date: 2024-01-21 22:19:46.244047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c698a505fe3d'
down_revision: Union[str, None] = 'bcb853436519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_power_usage', sa.Column('version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_power_usage', 'version')
    # ### end Alembic commands ###
